name: "Reusable AWS Deploy"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AWS_AK:
        required: true
      AWS_SK:
        required: true

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: "AWS Auth"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_AK }}
          aws-secret-access-key: ${{ secrets.AWS_SK }}
          aws-region: ${{ vars.aws_region }}

      - name: "Execution"
        run: |
          echo "Desplegando en ${{ inputs.environment }}..."
          aws sts get-caller-identity
